### ISSUE TITLE
Cholesky failure - g2o crashing in arm architecture

### ISSUE THREAD

**Issue by SYSUHPK** [mtlazaro/cg_mrslam#13]
Hello, sorry to bother you, cg_mrslam can be run on ubuntu16.04, but now I have a little error in the process of running on the new ubuntu16.04

Data set: the data set of the two robots you provide
While robots are running, command：
1.rosrun cg_mrslam cg_mrslam -idRobot 0 -nRobots 2 -scanTopic base_scan -mapFrame /robot_0/map -odomFrame /robot_0/odom -modality sim -publishMap -publishGraph -o testmrslam.g2o -baseAddr 127.0.0. __ns:=robot_0

2.rosrun cg_mrslam cg_mrslam -idRobot 1 -nRobots 2 -scanTopic base_scan -mapFrame /robot_1/map -odomFrame /robot_1/odom -modality sim -publishMap -publishGraph -o testmrslam.g2o -baseAddr 127.0.0. __ns:=robot_1

The following error appears on robot0 rather than robot1:
 "Cholesky failure, writing debug.txt (Hessian loadable by Octave)"
![image](https://user-images.githubusercontent.com/47689665/88394292-c7bbaf80-cdf1-11ea-89c1-436b32c1ff72.png)

I have tried many methods about they didn't work.
I look forward to receiving your reply.
Best wishes!

**Comment by mtlazaro** [comment]
Hi,
Sorry for the late answer.

So I understand you are using Ubuntu 16.04 with ROS Kinetic.
Please, give me some details about g2o version, and its dependency
libsuitesparse.

Could you also send the g2o files that are being generated until the point
it breaks.

**Comment by SYSUHPK** [comment]
Thanks a lot!!! I am so glad to recieve your reply!!! It really bother me for a long time.
According to what you say, I provide some information here(I can try to provide more information if it is not enough)
**1.version of g2o**
At first I thought it was caused by the g2o version. I tried two versions from https://github.com/RainerKuemmerle/g2o

![](https://cdn.nlark.com/yuque/0/2020/png/672521/1595923061788-4c292f24-638d-48db-b404-0e1b377111a6.png)

But both of them have the same problem when running cg_mrslam, and I still try it with the first one.
**2.My way to deploy g2o and cg_mrslam
2.1 I download and deploy g2o in my catkin_ws_g2o**
command:
in catkin_ws/src--git clone https://github.com/RainerKuemmerle/g2o.git(it is the lateset one)
build it according to what you say in cg_mrslam

![](https://cdn.nlark.com/yuque/0/2020/png/672521/1595923513361-b27ddb6a-20bc-4fbc-a72f-9290444d4963.png)

**2.2 deploy cg_mrslam in another catkin_ws_cg_mrslam
command:**
catkin_make -DCMAKE_BUILD_TYPE=Release
**3.about libsuitesparse(I am sorry I konw little about it and just provide these information)

![](https://cdn.nlark.com/yuque/0/2020/png/672521/1595924321273-2209cd84-bc32-423a-bcc3-c42facd4c6e5.png)

**4..g2o file about robot0, no wrong with robot1**

[robot-0-testmrslam.zip](https://github.com/mtlazaro/cg_mrslam/files/4987068/robot-0-testmrslam.zip)

**5.command to run cg_mrslam****
`roscore`
`rosbag play 2robots-hospital.bag`
```
rosrun cg_mrslam cg_mrslam -idRobot 0 -nRobots 2 -scanTopic base_scan -mapFrame  /robot_0/map -odomFrame /robot_0/odom -modality sim -publishMap -publishGraph -o 
testmrslam.g2o -baseAddr 127.0.0. __ns:=robot_0
```
```
rosrun cg_mrslam cg_mrslam -idRobot 1 -nRobots 2 -scanTopic base_scan -mapFrame  /robot_1/map -odomFrame /robot_1/odom -modality sim -publishMap -publishGraph -o 
testmrslam.g2o -baseAddr 127.0.0. __ns:=robot_1
```
**6.I can provide a video if you need.**

**Comment by mtlazaro** [comment]
Hi,

I just tried the example again and didn't have any issue.
I confirm that I have the same libsuitesparse version.
However, I have a different g2o version.
I work with an older stable version before big changes were made in g2o
regarding Eigen and architecture compilation flags.
You can checkout that version in this way:

git clone https://github.com/RainerKuemmerle/g2o.git
cd g2o
git checkout 4b9c2f5b68d14ad479457b18c5a2a0bce1541a90

I updated the Readme with these instructions.

You can test it and let me know if the problem persists.

Best,
Mayte.

**Comment by SYSUHPK** [comment]
Thanks a lot! I try it according to what you say.
I try it on ubuntu16.04(on TX2, I forget to mention this device last time, I remember that cg_mrslam also can work on TX2 before)
At first it reports like this one because of the arm arch when compiling g2o with your new command:
https://github.com/RainerKuemmerle/g2o/issues/218 
I fix it with command in https://github.com/RainerKuemmerle/g2o/pull/219 as below(I think it is also  an older stable version before big changes were made in g2o):
`git checkout a48ff8c42136f18fbe215b02bfeca48fa0c67507`
and it works
Then I try to build cg_mrslam and test, it finally works!!! Thanks  a lot!!! So I think what you say is right and maybe just need to add `git checkout a48ff8c42136f18fbe215b02bfeca48fa0c67507` when it is run on arm arch like TX2!

**Comment by mtlazaro** [comment]
Glad to hear that.
From the beginning I thought it was a compilation issue or some problem with the g2o version.

I change the name of this issue to be more informative, so it can help future users.
