### ISSUE TITLE
Publishing graph before creating publisher

### ISSUE THREAD

**Issue by MaxGsomGsom** [mtlazaro/cg_mrslam#5]
It crashes if compiled in debug configuration. You need to  call `graphPublisher.start();` before `graphPublisher.publishGraph();`

https://github.com/mtlazaro/cg_mrslam/blob/31667f3b316c925273bf385be32b8d525bba181e/src/cg_mrslam.cpp#L186-L193

**Comment by mtlazaro** [comment]
You are completely right.
Funny that it didn't crash before at that point.

Fixed in 07e1fc49c2e5e7eca72f2532312ae25b14b2d1d1

Thanks,
Mayte.
